-- MySQL Script generated by MySQL Workbench
-- Tue Jun  1 15:36:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AstronomicalDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AstronomicalDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AstronomicalDatabase` DEFAULT CHARACTER SET utf8 ;
USE `AstronomicalDatabase` ;

-- -----------------------------------------------------
-- Table `AstronomicalDatabase`.`GALAXY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstronomicalDatabase`.`GALAXY` (
  `NAME` VARCHAR(30) NOT NULL,
  `DECLINATION` VARCHAR(20) NULL,
  `RIGHT_ASCENSION` VARCHAR(20) NULL,
  `TYPE` VARCHAR(20) NULL,
  `DISTANCE` VARCHAR(20) NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstronomicalDatabase`.`CONSTELLATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstronomicalDatabase`.`CONSTELLATION` (
  `NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstronomicalDatabase`.`STAR_SYSTEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstronomicalDatabase`.`STAR_SYSTEM` (
  `NAME` VARCHAR(20) NOT NULL,
  `DISTANCE` VARCHAR(20) NULL,
  `DECLINATION` VARCHAR(20) NULL,
  `RIGHT_ASCENSION` VARCHAR(20) NULL,
  `GALAXY_NAME` VARCHAR(20) NOT NULL,
  `CONSTELLATION_NAME` VARCHAR(20) NULL,
  PRIMARY KEY (`NAME`),
  INDEX `fk_star_system_galaxy_idx` (`GALAXY_NAME` ASC) VISIBLE,
  INDEX `fk_star_system_Constellation1_idx` (`CONSTELLATION_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_star_system_galaxy`
    FOREIGN KEY (`GALAXY_NAME`)
    REFERENCES `AstronomicalDatabase`.`GALAXY` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_star_system_Constellation1`
    FOREIGN KEY (`CONSTELLATION_NAME`)
    REFERENCES `AstronomicalDatabase`.`CONSTELLATION` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstronomicalDatabase`.`STAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstronomicalDatabase`.`STAR` (
  `NAME` VARCHAR(30) NOT NULL,
  `MASS` VARCHAR(20) NULL,
  `RADIUS` VARCHAR(20) NULL,
  `SPECTRAL_CLASS` VARCHAR(10) NULL,
  `MAGNITUDE` VARCHAR(10) NULL,
  `STAR_SYSTEM_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`NAME`),
  INDEX `fk_star_star_system1_idx` (`STAR_SYSTEM_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_star_star_system1`
    FOREIGN KEY (`STAR_SYSTEM_NAME`)
    REFERENCES `AstronomicalDatabase`.`STAR_SYSTEM` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstronomicalDatabase`.`PLANET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstronomicalDatabase`.`PLANET` (
  `NAME` VARCHAR(30) NOT NULL,
  `TYPE` VARCHAR(10) NULL,
  `MASS` VARCHAR(20) NULL,
  `RADIUS` VARCHAR(20) NULL,
  `SEMI_MAJOR_AXIS` VARCHAR(20) NULL,
  `ORBITAL_ECCENTRICITY` VARCHAR(20) NULL,
  `STAR_SYSTEM_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`NAME`),
  INDEX `fk_Planet_star_system1_idx` (`STAR_SYSTEM_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_Planet_star_system1`
    FOREIGN KEY (`STAR_SYSTEM_NAME`)
    REFERENCES `AstronomicalDatabase`.`STAR_SYSTEM` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AstronomicalDatabase`.`SATELLITE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AstronomicalDatabase`.`SATELLITE` (
  `NAME` VARCHAR(30) NOT NULL,
  `TYPE` VARCHAR(20) NULL,
  `MASS` VARCHAR(20) NULL,
  `RADIUS` VARCHAR(20) NULL,
  `SEMI_MAJOR_AXIS` VARCHAR(20) NULL,
  `ORBITAL_ECCENTRICITY` VARCHAR(20) NULL,
  `PLANET_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`NAME`),
  INDEX `fk_Satellite_Planet1_idx` (`PLANET_NAME` ASC) VISIBLE,
  CONSTRAINT `fk_Satellite_Planet1`
    FOREIGN KEY (`PLANET_NAME`)
    REFERENCES `AstronomicalDatabase`.`PLANET` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
